
// Import tonic (gRPC framework) and the generated Rust service types
use tonic::transport::Server;
pub mod service;
use service::key_service::MyKeyService;
use service::signing_service::MySigningService;
use service::signing_service::SigningSessionStore;
use service::health_service::MyHealthService;
//use custody::key_service_server::KeyServiceServer;
//use custody::signing_service_server::SigningServiceServer;
//use custody::health_service_server::HealthServiceServer;

// Load the generated Rust code from custody.proto (auto-generated by tonic_build)
pub mod custody {
    tonic::include_proto!("custody");
}

// Start the gRPC server using the Tokio async runtime
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Set up logging (e.g., info!, error!, etc.)
    tracing_subscriber::fmt::init();

    // Output simple startup message to the console (visible to user)
    println!("Starting Custody gRPC Server on [::1}:50051");

    // Create a shared store for signing sessions
    let signing_store = SigningSessionStore::default();
    let signing_service = MySigningService {
        store: Arc::new(signing_store),
    };

    // Start the gRPC server and bind our service handlers (to be implemented)
    server::builder()
        .add_service(KeyServiceServer::new(MyKeyService::default()))
        .add_service(SigningServiceServer::new(MySigningService::default()))
        .add_service(HealthServiceServer::new(MyHealthService::default()))
        .serve("[::1]:50051".parse()?)
        .await?;
    Ok(())
}

// to run the gRPC server
// cargo run -p custody_server

// then check health endpoint useing grpcurl
// grpcurl -plaintext localhost:50051 custody.HealthService/Check